// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public class JerarquiasModel
{
    public JerarquiasModel()
    {
            
    }
    public JerarquiasModel(Jerarquias Objeto)
    {
        JerarquiaID = Objeto.JerarquiaID;
        Nombre  = Objeto.Nombre;
    }
    [Key]
    public int JerarquiaID { get; set; }

    [Required(ErrorMessage = "Campo Requerido")]
    [StringLength(50)]
    public string Nombre { get; set; }

    public Jerarquias ConvertBD()
    {
        return new Jerarquias { 
            JerarquiaID = JerarquiaID,
            Nombre = Nombre
        };
    }


}