// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public partial class Area
{
    [Key]
    public int AreaID { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    public Guid CodigoDaloo { get; set; }

    [InverseProperty("Area")]
    public virtual ICollection<Ruta> Ruta { get; set; } = new List<Ruta>();

    [InverseProperty("Area")]
    public virtual ICollection<UsuarioArea> UsuarioArea { get; set; } = new List<UsuarioArea>();
}