// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public partial class Bitacora
{
    [Key]
    public int BitacoraID { get; set; }

    [Required]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [Required]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Fecha { get; set; }
}