// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public partial class CumplimientoRequisito
{
    [Key]
    public int CumplimientoRequisitoID { get; set; }

    public int RequisitoID { get; set; }

    public int ColaboradorID { get; set; }

    [Column(TypeName = "date")]
    public DateTime FechaRegistro { get; set; }

    [Column(TypeName = "date")]
    public DateTime FechaObtencion { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string URLEvidencia { get; set; }

    public int AprobadoPorSupervisor { get; set; }

    public int PlanDesarrolloID { get; set; }

    [Column(TypeName = "date")]
    public DateTime FechaArpobacion { get; set; }

    [ForeignKey("PlanDesarrolloID")]
    [InverseProperty("CumplimientoRequisito")]
    public virtual PlanesDesarrolloProfesional PlanDesarrollo { get; set; }

    [ForeignKey("RequisitoID")]
    [InverseProperty("CumplimientoRequisito")]
    public virtual Requisito Requisito { get; set; }
}