// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public partial class Jerarquias
{
    [Key]
    public int JerarquiaID { get; set; }

    [Required]
    [StringLength(10)]
    public string Nombre { get; set; }

    [InverseProperty("Jerarquia")]
    public virtual ICollection<Usuario> Usuario { get; set; } = new List<Usuario>();
}