// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public partial class PlanDesarrolloProfesional
{
    [Key]
    public int PlanDesarrolloID { get; set; }

    public int ColaboradorID { get; set; }

    [Column(TypeName = "date")]
    public DateTime FechaInicio { get; set; }

    public int Estado { get; set; }

    public int RangoID { get; set; }

    public bool Finalizado { get; set; }

    [ForeignKey("ColaboradorID")]
    [InverseProperty("PlanDesarrolloProfesional")]
    public virtual Usuario Colaborador { get; set; }

    [InverseProperty("PlanDesarrollo")]
    public virtual ICollection<CumplimientoRequisito> CumplimientoRequisito { get; set; } = new List<CumplimientoRequisito>();
}