// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public partial class Rango
{
    [Key]
    public int RangoID { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string NombreRango { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    public int RutaID { get; set; }

    [InverseProperty("Rango")]
    public virtual ICollection<PlanDesarrolloProfesional> PlanDesarrolloProfesional { get; set; } = new List<PlanDesarrolloProfesional>();

    [InverseProperty("Rango")]
    public virtual ICollection<Requisito> Requisito { get; set; } = new List<Requisito>();

    [ForeignKey("RutaID")]
    [InverseProperty("Rango")]
    public virtual Ruta Ruta { get; set; }
}