// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public partial class Rol
{
    [Key]
    public int RolID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string NombreRol { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [InverseProperty("Rol")]
    public virtual ICollection<Usuario> Usuario { get; set; } = new List<Usuario>();
}