// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public partial class Ruta
{
    [Key]
    public int RutaID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string NombreRuta { get; set; }
     
    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    public int AreaID { get; set; }

    [ForeignKey("AreaID")]
    [InverseProperty("Ruta")]
    public virtual Area Area { get; set; }

    [InverseProperty("Ruta")]
    public virtual ICollection<Rango> Rango { get; set; } = new List<Rango>();
}