// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public partial class UsuarioJerarquias
{
    [Key]
    public int Id { get; set; }

    public int UsuarioID { get; set; }

    public int SupervisorID { get; set; }

    [ForeignKey("SupervisorID")]
    [InverseProperty("UsuarioJerarquiasSupervisor")]
    public virtual Usuario Supervisor { get; set; }

    [ForeignKey("UsuarioID")]
    [InverseProperty("UsuarioJerarquiasUsuario")]
    public virtual Usuario Usuario { get; set; }
}