// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public partial class UsuarioArea
{
    public int UsuarioID { get; set; }

    public int AreaID { get; set; }

    [Key]
    public int UsuarioAreaID { get; set; }

    [ForeignKey("AreaID")]
    [InverseProperty("UsuarioArea")]
    public virtual Area Area { get; set; }

    [ForeignKey("UsuarioID")]
    [InverseProperty("UsuarioArea")]
    public virtual Usuario Usuario { get; set; }
}