// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public partial class UsuarioRuta
{
    public int UsuarioID { get; set; }

    public int AreaID { get; set; }

    [Key]
    public int UsuarioAreaID { get; set; }

    public bool? Eliminado { get; set; }

    [ForeignKey("AreaID")]
    [InverseProperty("UsuarioArea")]
    public virtual Area Area { get; set; }

    [ForeignKey("RutaID")]
    [InverseProperty("UsuarioRuta")]
    public virtual Ruta Ruta { get; set; }

    public object NombreRuta { get; set; }
    public object DescripcionRuta { get; set; }
}