// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public class RequisitoViewModel
{
    public RequisitoViewModel() { }

    [Key]
    [Required]
    public int RequisitoID { get; set; }

    [Required]
    [StringLength(50)]
    public string NombreRequisito { get; set; }

    public int Estado { get; set; }

    public int RangoID { get; set; }

    public string RangoNombre { get; set; }

}