// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public class RequisitoModel
{
    public RequisitoModel()
    {

    }
    public RequisitoModel(Requisito Objeto)
    {
        RequisitoID = Objeto.RequisitoID;
        NombreRequisito = Objeto.NombreRequisito;
        Estado = Objeto.Estado;
        RangoID = Objeto.RangoID;
    }
    [Key]
    public int RequisitoID { get; set; }

    [Required(ErrorMessage = "Campo Requerido")]
    [StringLength(100)]
    public string NombreRequisito { get; set; }

    public int Estado { get; set; }

    public int RangoID { get; set; }

    [Required(ErrorMessage = "El campo Requisito es obligatorio.")]
    public int RequisitoSeleccionado { get; set; }

public Requisito ConvertBD()
    {
        return new Requisito
        {
            RequisitoID = RequisitoID,
            NombreRequisito = NombreRequisito,
            Estado = Estado,
            RangoID = RangoID
    };
    }


}