// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public class RangoModel
{
    public RangoModel()
    {

    }
    public RangoModel(Rango Objeto)
    {
        RangoID = Objeto.RangoID;
        NombreRango = Objeto.NombreRango;
        Descripcion = Objeto.Descripcion;
        RutaID = Objeto.RutaID;
    }

    [Key]
    public int RangoID { get; set; }

    [Required(ErrorMessage = "Campo Requerido")]
    [StringLength(250)]
    [Unicode(false)]
    public string NombreRango { get; set; }

    [Required(ErrorMessage = "Campo Requerido")]
    [StringLength(250)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    public int RutaID { get; set; }

    public Rango ConvertBD()
    {
        return new Rango
        {
            RangoID = RangoID,
            NombreRango = NombreRango,
            Descripcion = Descripcion,
            RutaID = RutaID
        };
    }
}