// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlanDesarrolloProfesional.Models.Models;

public class RangoViewModel
{
    public RangoViewModel() { }

    [Key]
    public int RangoID { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string NombreRango { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    public int RutaID { get; set; }

}